import { Component, output } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatTableModule } from '@angular/material/table';
import { Paginator, Table } from 'lib';

@Component({
  selector: 'cdev-course',
  imports: [Table, MatIconModule, MatTableModule, Paginator],
  templateUrl: './course.html',
  styleUrl: './course.scss',
})
export class Course {
  onSelectedRow = output<any>();

  dataOriginal = [
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
    { name: 'Angular', level: 'Advanced' },
    { name: 'React', level: 'Intermediate' },
    { name: 'Vue', level: 'Beginner' },
  ];

  data: any[] = []

  metaColumns = [
    { label: 'Course Name', field: 'name' },
    { label: 'Difficulty Level', field: 'level' },
  ];

  constructor() {
    this.loadDataByPage(0)
  }

  loadDataByPage(pageIndex: number) {
    const pageSize = 20;
    const startIndex = pageIndex * pageSize;
    const endIndex = startIndex + pageSize;
    this.data = this.dataOriginal.slice(startIndex, endIndex);
  }

  selectedRow(row: any) {
    this.onSelectedRow.emit(row);
  }
}
